pizzaria/urls.py
from django.urls import path

from . import views

app_name = 'pizzaria'

urlpatterns = [
    path('',views.index,name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('new_comment/<int:pizza_id>/',views.new_comment,name='new_comment'),
]

pizzas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzaria.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pizzaria/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='img',blank=True,null=True)

    def __str__(self):
        return self.pizza_name



class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=40)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.topping_name


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comments = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comments
    

    

pizzaria/forms.py
from django import forms

from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comments']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

pizzaria/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *

# Create your views here.
def index(request):
    return render(request, 'pizzaria/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('pizza_name')

    context = {'all_pizzas':pizzas}                

    return render(request, 'pizzaria/pizzas.html', context)


def pizza(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)

    toppings = Topping.objects.filter(pizza=p)

    comment = Comment.objects.filter(pizza=p)     

    context = {'pizza':p, 'toppings':toppings, 'comment':comment}

    return render(request, 'pizzaria/pizza.html', context)

def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzaria:pizza',pizza_id=pizza_id)
    
    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzaria/new_comment.html', context)

pizzaria/templates/pizzaria/base.html
{% load bootstrap4 %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
     shrink-to-fit=no">

    <title>Pizzeria</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>




<body>

    <style>
        body {
          background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWY05tqt0MlKB9tyU_4DGbKtRLm9gdAfQ9FA&usqp=CAU');
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: 100% 100%;
        }
        </style>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    
        <a class="navbar-brand" href="{% url 'pizzaria:index'%}">
            Pizzeria</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
     data-target="#navbarCollapse" aria-controls="navbarCollapse"
     aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pizzaria:pizzas'%}">
                 Pizzas</a></li>
         </ul>
    </div>
    </nav>


    <main role="main" class="container">


        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
         </div>
         <body>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

pizzaria/templates/pizzaria/index.html
{% extends "pizzaria/base.html" %}



{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Welcome to Campbell's Pizza's!</h1>
    <pre>
      <span style="color:palevioletred; font-size:large;">
          "No matter how hard school gets, all I do is order a large pizza 
          and I'm fine!" -Campbell Wilford, freshman year 
  </span>
  </pre>

</div>




  {% endblock page_header %}

  {% block content %}

{% endblock content %}



 

pizzaria/templates/pizzaria/new_comment.html
{% extends "pizzaria/base.html" %}

{% block content %}

<p><a href="{% url 'pizzaria:pizza' pizza.id %}">{{pizza}}</a></p>

<p>Add new comment:</p>

<form action="{% url 'pizzaria:new_comment' pizza.id %}" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add comment</button>

</form>


{% endblock content %}

 

pizzaria/templates/pizzaria/pizza.html
{% extends "pizzaria/base.html" %}

{% block page_header %}
    <h3><span style="color:palevioletred">{{pizza}}</span></h3>
{% endblock page_header %}

{% block content %}
<p>
  {% load static %} 
  <img src="{{ Pizza.image.url }}">
</p>
<ul>
    {% for t in toppings %}

    <span style="color:palevioletred"><li><h3> {{ t.topping_name }} </h3></li></span>

    {% empty %}
    <li><h3> No toppings for this pizza have been added yet.</h3></li>
    {% endfor %}

</ul>

<p>
    <h3><a href="{% url 'pizzaria:new_comment' pizza.id %}">Add a new comment</a></h3>
</p>

<ul>
  {% for comments in comments %}
  <div class="background">
      <span style="color:white">
          <h4 class="card-header">
          {{ comments.comments|linebreaks }}
          </h4>
      </span>
      <span style="color:white"><div class="card-body">
      {{ r.date_added|date:'M d, Y H:i' }}
    </span>
        </div>
    </div>


    {% empty %}
    <P> No comments for this pizza have been added yet.</p>
    {% endfor %}

</ul>





{% endblock content %}

 

pizzaria/templates/pizzaria/pizzas.html
{% extends "pizzaria/base.html" %} 

{% block content %} 

<h3>
  <p>
      <span style="text-decoration: underline; color:palevioletred"> Pizzas </span>
  </p>
</h3>

<ul>
  {% for pizza in all_pizzas %}
  <li> 
    <a href="{% url 'pizzaria:pizza' pizza.id%}">{{pizza}}</a>
  </li>

  {% empty %} 
  <li> No pizzas have been added yet. </li>
  {% endfor %}
</ul>

{% endblock content %} 